id: A779BB77B
title: Prayer for the Swift Rebirth of Jamyang Khyentse Wangpo
type: translation
pechas:
- I3303AD6D
- I4C03CB90
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:37:49.004750
  last_modified_at: 2023-01-04 12:37:49.004755
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  I3303AD6D/663B: CCCE
  I4C03CB90/0FE8: CCCE
